window.PIOS_DEMO = {
  project: {
    id: "OOLTOOL-MVP",
    name: "Subscription Intelligence",
    owner: "Hardik",
    version: "1.0",
    status: "Human Review Open",
    validationReadiness: "CONDITIONAL",
    releaseDecision: "PENDING",
  },
  summary: {
    files: 1,
    pages: 26,
    requirements: 24,
    businessRules: 7,
    dependencies: 19,
    risks: 5,
    questions: 11,
    validationAreas: 6,
    scenarios: 22,
    evidenceItems: 14,
  },
  requirementText:
    "When a customer upgrades their subscription, every active session must remain valid and receive the updated entitlements without forcing logout.",
  requirements: [
    {
      id: "REQ-1.2",
      title: "Session continuity on upgrade",
      status: "Needs clarification",
      priority: "Critical",
      objective: "Upgrade customer access without interrupting active authenticated sessions.",
      actors: ["Customer", "Subscription Service", "Identity Service", "Entitlement Engine"],
      ac: [
        "Active sessions remain valid after upgrade",
        "Entitlements refresh without revoking authentication",
        "User reaches updated plan features without re-login",
      ],
      links: { rules: ["BR-01"], deps: ["DEP-04", "DEP-05"], risks: ["RISK-02"], questions: ["GAP-03"], evidence: ["EVD-001"] },
    },
    {
      id: "REQ-1.4",
      title: "Payment and entitlement synchronization",
      status: "In review",
      priority: "Critical",
      objective: "Payment success must sync subscription and entitlement state atomically.",
      actors: ["Payment Service", "Subscription Service", "Entitlement Engine"],
      ac: [
        "Successful payment updates subscription state",
        "Entitlement engine receives confirmed plan change",
        "Partial failure triggers reconciliation path",
      ],
      links: { rules: ["BR-02"], deps: ["DEP-01", "DEP-02", "DEP-03"], risks: ["RISK-05"], questions: ["GAP-04"], evidence: ["EVD-002"] },
    },
    {
      id: "REQ-1.5",
      title: "Multiple active subscriptions handling",
      status: "Draft",
      priority: "Medium",
      objective: "Define behavior when a customer has more than one active subscription context.",
      actors: ["Customer", "Billing", "Entitlement Engine"],
      ac: ["System identifies primary subscription context", "Conflicting entitlements are resolved by rule"],
      links: { rules: ["BR-03"], deps: ["DEP-03"], risks: ["RISK-08"], questions: ["GAP-05"], evidence: [] },
    },
  ],
  rules: [
    { id: "BR-01", title: "Entitlements refresh without revoking auth", requirementId: "REQ-1.2", severity: "Critical" },
    { id: "BR-02", title: "Payment success required before entitlement grant", requirementId: "REQ-1.4", severity: "Critical" },
    { id: "BR-03", title: "Primary subscription wins on conflict", requirementId: "REQ-1.5", severity: "Medium" },
  ],
  dependencies: [
    { id: "DEP-01", from: "Payment", to: "Subscription", type: "API", requirementId: "REQ-1.4" },
    { id: "DEP-02", from: "Subscription", to: "Entitlement", type: "DATA", requirementId: "REQ-1.4" },
    { id: "DEP-03", from: "Entitlement", to: "Active Sessions", type: "DATA", requirementId: "REQ-1.2" },
    { id: "DEP-04", from: "Identity Service", to: "Active Sessions", type: "SYSTEM", requirementId: "REQ-1.2" },
    { id: "DEP-05", from: "Active Sessions", to: "Notification", type: "API", requirementId: "REQ-1.2" },
  ],
  risks: [
    {
      id: "RISK-02",
      title: "Session expiry during entitlement refresh",
      level: "Critical",
      owner: "RIE",
      requirementId: "REQ-1.2",
      why: "Users may be logged out while plan upgrade is processing.",
    },
    {
      id: "RISK-05",
      title: "Paid plan active but access unavailable",
      level: "Critical",
      owner: "RIE",
      requirementId: "REQ-1.4",
      why: "Partial upgrade can desync payment and entitlement state.",
    },
    {
      id: "RISK-08",
      title: "Ambiguous multi-subscription behavior",
      level: "Medium",
      owner: "RIE",
      requirementId: "REQ-1.5",
      why: "Missing product rule for conflicting entitlements.",
    },
  ],
  questions: [
    { id: "GAP-03", text: "Can the upgrade be rolled back after payment succeeds?", priority: "Critical", requirementId: "REQ-1.4", riskId: "RISK-05" },
    { id: "GAP-04", text: "Who owns payment retry and reconciliation?", priority: "High", requirementId: "REQ-1.4", riskId: "RISK-05" },
    { id: "GAP-05", text: "How should multiple active subscriptions be handled?", priority: "Medium", requirementId: "REQ-1.5", riskId: "RISK-08" },
    { id: "GAP-02", text: "Should active sessions ever expire during entitlement refresh?", priority: "Critical", requirementId: "REQ-1.2", riskId: "RISK-02" },
  ],
  findings: [
    {
      id: "f1",
      title: "Business objective",
      source: "REQ-1.2",
      confidence: 98,
      impact: "High",
      evidence: "Strong",
      text: "Upgrade customer access without interrupting active authenticated sessions.",
      quote: "When a customer upgrades their subscription, all active sessions must remain valid.",
      links: ["REQ-1.2", "DEP-03", "EVD-001"],
    },
    {
      id: "f2",
      title: "Critical rule",
      source: "REQ-1.2",
      confidence: 96,
      impact: "Critical",
      evidence: "Strong",
      text: "Entitlements must refresh without revoking authentication tokens for active sessions.",
      quote: "every active session must remain valid and receive the updated entitlements",
      links: ["BR-01", "REQ-1.2", "EVD-001"],
    },
    {
      id: "f3",
      title: "Highest dependency",
      source: "REQ-1.4",
      confidence: 89,
      impact: "Critical",
      evidence: "Medium",
      text: "Payment, subscription, entitlement, and session services must stay synchronized.",
      quote: "Payment → Subscription → Entitlement → Active Sessions",
      links: ["DEP-01", "DEP-02", "DEP-03", "RISK-05"],
    },
    {
      id: "f4",
      title: "Primary risk",
      source: "REQ-1.4",
      confidence: 92,
      impact: "Critical",
      evidence: "Medium",
      text: "Partial upgrade can leave paid plan active while purchased access is unavailable.",
      quote: "Paid plan active but purchased access unavailable",
      links: ["RISK-05", "GAP-03"],
    },
    {
      id: "f5",
      title: "Decision required",
      source: "GAP-03",
      confidence: 86,
      impact: "High",
      evidence: "Weak",
      text: "Rollback ownership after successful payment is undefined and needs a product decision.",
      quote: "Can the upgrade be rolled back after payment succeeds?",
      links: ["GAP-03", "REQ-1.4"],
    },
    {
      id: "f6",
      title: "Evidence outcome",
      source: "NFR-2.3",
      confidence: 94,
      impact: "High",
      evidence: "Strong",
      text: "Validation must prove UI, API, database, logs, and business outcome remain aligned.",
      quote: "UI → API → DB → Logs → Outcome",
      links: ["EVD-002", "EVD-003"],
    },
  ],
  evidence: [
    { id: "EVD-001", type: "Screenshot + Trace", title: "Session remains after upgrade", requirementId: "REQ-1.2", status: "Captured" },
    { id: "EVD-002", type: "API + DB", title: "Payment and entitlement sync proof", requirementId: "REQ-1.4", status: "Captured" },
    { id: "EVD-003", type: "Logs", title: "Entitlement refresh log chain", requirementId: "REQ-1.2", status: "Gap" },
  ],
  journeys: [
    { id: "JRN-ONBOARDING-001", name: "Customer Onboarding", status: "Healthy", coverage: 91 },
    { id: "JRN-UPGRADE-001", name: "Subscription Upgrade", status: "Warning", coverage: 78 },
    { id: "JRN-SESSION-001", name: "Session Continuity", status: "At Risk", coverage: 64 },
  ],
  attention: [
    { id: "att-1", tone: "red", title: "3 requirements need clarification", detail: "Missing session rollback rule", href: "workspace.html#requirements", owner: "RIE" },
    { id: "att-2", tone: "amber", title: "Validation readiness is CONDITIONAL", detail: "3 warnings · evidence linked", href: "workspace.html#air", owner: "AIR" },
    { id: "att-3", tone: "amber", title: "2 release blockers pending review", detail: "RI decision not yet formed", href: "workspace.html#ri", owner: "RI" },
    { id: "att-4", tone: "green", title: "7 evidence items ready to inspect", detail: "View Evidence", href: "workspace.html#evidence", owner: "Evidence" },
  ],
  knowledge: [
    { id: "K-01", type: "Lessons learned", title: "Delayed events require explicit recovery ownership", status: "Verified" },
    { id: "K-02", type: "Root cause", title: "Session revocation triggered by entitlement refresh", status: "Verified" },
    { id: "K-03", type: "Test pattern", title: "Multi-layer subscription upgrade validation", status: "Reusable" },
    { id: "K-04", type: "API pattern", title: "Idempotent event processing and reconciliation", status: "Reusable" },
    { id: "K-05", type: "Validation template", title: "UI → API → DB → Logs → Outcome checklist", status: "Verified" },
    { id: "K-06", type: "Common risk", title: "Paid plan active but purchased access unavailable", status: "Observed" },
  ],
  aiPrompts: [
    {
      id: "p1",
      label: "Explain this requirement",
      answer: "Upgrade customer access without interrupting active sessions. Session continuity is part of a successful plan upgrade.",
    },
    {
      id: "p2",
      label: "Find dependencies",
      answer: "Customer, subscription service, identity service, and entitlement engine must stay synchronized through payment confirmation.",
    },
    {
      id: "p3",
      label: "Generate test scenarios",
      answer: "22 scenarios covering happy path upgrade, failed payment, entitlement lag, multi-session refresh, and rollback gaps.",
    },
    {
      id: "p4",
      label: "Show business rules",
      answer: "Entitlements must refresh without revoking authentication. Payment success is required before entitlement grant.",
    },
    {
      id: "p5",
      label: "What should QA validate?",
      answer: "UI plan badge, API entitlement payload, DB subscription row, auth token validity, and final business outcome access.",
    },
    {
      id: "p6",
      label: "Generate test cases",
      answer: "TC-001—028 cover session continuity, payment sync, entitlement refresh, and evidence capture across layers.",
    },
  ],
  sourceEvidence: {
    document: "sample11.pdf",
    page: "Page 2",
    paragraph: "Paragraph 4",
    requirementId: "REQ-1.2",
    before: "Customers may change their subscription plan at any time after payment authorization.",
    highlight: "When a customer upgrades their subscription, all active sessions must remain valid.",
    after: "The platform must record the completed upgrade and preserve an auditable history of the change.",
  },
  depGraph: [
    { id: "DEP-ROOT", name: "Subscription Upgrade", type: "Root", criticality: "Critical", role: "Primary requirement outcome", root: true },
    { id: "DEP-SUB", name: "Subscription", type: "System", criticality: "Critical", role: "Receives upgrade request", openId: "DEP-01" },
    { id: "DEP-PAY", name: "Payment", type: "API", criticality: "Critical", role: "Confirms transaction", openId: "DEP-01" },
    { id: "DEP-ENT", name: "Entitlement", type: "Data", criticality: "Critical", role: "Consumes plan change", openId: "DEP-02" },
    { id: "DEP-SES", name: "Active Sessions", type: "Data", criticality: "Critical", role: "Receives refreshed claims", openId: "DEP-03" },
    { id: "DEP-NOT", name: "Notification", type: "API", criticality: "Medium", role: "Receives completion event", openId: "DEP-05" },
    { id: "DEP-AUD", name: "Audit", type: "Business", criticality: "High", role: "Records lifecycle events", openId: "DEP-04" },
    { id: "DEP-BIL", name: "Billing", type: "Business", criticality: "High", role: "Consumes subscription state", openId: "DEP-02" },
  ],
  traceRows: [
    { source: "Subscription_FRD.pdf · p2", requirement: "REQ-1.2", rule: "BR-01", dependency: "Active Sessions", risk: "RISK-02", missing: false },
    { source: "Subscription_FRD.pdf · p4", requirement: "REQ-1.4", rule: "BR-02", dependency: "Payment", risk: "RISK-05", missing: false },
    { source: "Subscription_FRD.pdf · p6", requirement: "GAP-03", rule: null, dependency: "Entitlement", risk: "RISK-05", missing: true },
    { source: "NFR_Pack.pdf · p1", requirement: "REQ-1.5", rule: "BR-03", dependency: "Entitlement", risk: "RISK-08", missing: false },
  ],
  reviewGates: [
    { id: "GATE-01", q: "Has the upgrade path been clarified with product?", score: 100, answer: "YES", related: ["REQ-1.2", "REQ-1.4"] },
    { id: "GATE-02", q: "Are payment and entitlement sync rules reviewed?", score: 100, answer: "YES", related: ["BR-01", "BR-02", "DEP-01"] },
    { id: "GATE-03", q: "Is session continuity acceptance criteria approved?", score: 72, answer: "PARTIAL", related: ["REQ-1.2", "GAP-02"] },
    { id: "GATE-04", q: "Is rollback ownership after payment defined?", score: 0, answer: "NO", related: ["GAP-03", "RISK-05"] },
  ],
  documents: [
    {
      id: "DOC-SAMPLE",
      title: "sample11.pdf",
      detail: "Primary uploaded requirement source used in this demo analysis.",
      requirementId: "REQ-1.2",
      links: ["REQ-1.2", "EVD-001"],
    },
    {
      id: "DOC-FRD",
      title: "Subscription_FRD.pdf",
      detail: "Functional requirements document covering upgrade, payment, and entitlement flows.",
      requirementId: "REQ-1.4",
      links: ["REQ-1.2", "REQ-1.4", "BR-01"],
    },
    {
      id: "DOC-NFR",
      title: "NFR_Pack.pdf",
      detail: "Non-functional pack including evidence-outcome expectations across UI → API → DB → Logs.",
      requirementId: "REQ-1.5",
      links: ["EVD-002", "EVD-003", "JRN-UPGRADE-001"],
    },
  ],
  topics: {
    requirements: {
      kicker: "RIE",
      title: "Requirements intelligence",
      summary: "24 structured requirements. Critical focus is session continuity and payment–entitlement sync.",
      stats: "8 need clarification · 3 critical paths",
      related: ["REQ-1.2", "REQ-1.4", "REQ-1.5"],
      href: "workspace.html#requirements",
      cta: "Open requirements",
    },
    rules: {
      kicker: "RIE",
      title: "Business rules",
      summary: "7 business rules extracted. Entitlement refresh must not revoke authentication.",
      related: ["BR-01", "BR-02", "BR-03"],
      href: "workspace.html#requirements",
      cta: "Open rules",
    },
    dependencies: {
      kicker: "RIE",
      title: "Dependencies",
      summary: "19 dependencies across Payment → Subscription → Entitlement → Active Sessions.",
      related: ["DEP-01", "DEP-02", "DEP-03", "DEP-04", "DEP-05"],
      href: "workspace.html#dependencies",
      cta: "Open dependencies",
    },
    risks: {
      kicker: "RIE",
      title: "Risks",
      summary: "5 risks prioritized. Highest: paid plan active while purchased access is unavailable.",
      related: ["RISK-02", "RISK-05", "RISK-08"],
      href: "workspace.html#risks",
      cta: "Open risks",
    },
    questions: {
      kicker: "RIE",
      title: "Open questions",
      summary: "11 clarification questions remain. Rollback ownership after payment is unresolved.",
      related: ["GAP-03", "GAP-02", "GAP-04", "GAP-05"],
      href: "workspace.html#questions",
      cta: "Open questions",
    },
    readiness: {
      kicker: "AIR",
      title: "Validation readiness · CONDITIONAL",
      summary: "AIR reports CONDITIONAL readiness. Evidence is linked with 3 warnings and 0 blockers. This is not a release decision.",
      stats: "22 scenarios · 14 evidence items · coverage warnings on session continuity",
      related: ["JRN-UPGRADE-001", "EVD-001", "EVD-003", "RISK-05"],
      href: "workspace.html#air",
      cta: "Open AIR",
    },
    release: {
      kicker: "RI",
      title: "Release decision · PENDING",
      summary: "RI owns GO / CONDITIONAL GO / NO-GO. Decision remains PENDING until humans finish review and acknowledge gaps.",
      related: ["RISK-05", "GAP-03", "EVD-001"],
      href: "workspace.html#ri",
      cta: "Open RI",
    },
    evidence: {
      kicker: "Evidence",
      title: "Evidence inventory",
      summary: "Shared evidence identity across products. One gap remains on entitlement refresh log chain.",
      related: ["EVD-001", "EVD-002", "EVD-003"],
      href: "workspace.html#evidence",
      cta: "Open evidence",
    },
    knowledge: {
      kicker: "Knowledge",
      title: "Reusable knowledge",
      summary: "Lessons and patterns captured from subscription upgrade intelligence.",
      related: ["K-01", "K-02", "K-03", "K-05"],
      href: "workspace.html#knowledge",
      cta: "Open knowledge",
    },
    project: {
      kicker: "Project",
      title: "Subscription Intelligence",
      summary: "Demo project OOLTOOL-MVP. Owner Hardik · Version 1.0 · Human review open.",
      stats: "Validation CONDITIONAL · Release PENDING",
      related: ["REQ-1.2", "JRN-UPGRADE-001", "EVD-001"],
      href: "workspace.html",
      cta: "Open workspace",
    },
    files: {
      kicker: "Input",
      title: "Source files",
      summary: "Uploaded / pasted requirement sources used for this analysis run.",
      related: ["DOC-SAMPLE", "DOC-FRD", "REQ-1.2"],
      href: "start.html",
      cta: "Back to input",
    },
  },
};

window.PIOS_STATE_KEY = "pios-design-demo-state";
